### ISSUE TITLE
Simplify3d gcode files don't work with 3dwox1

### ISSUE THREAD

**Issue by bbulkow** [bobotmedia/3DWOX1#1]
Although these profiles do match, it seems that the gcode files generated by simplify3d aren't compatible with the 3dwox1. They are said to be "not the right type".
Different internet sources say one has to include the first three lines of printer and type, which could be included in the "include gcode".
Since the author clearly has Simplify3d working with these printers, a bit of a hint in "howto" would be very helpful!

**Comment by bobotmedia** [comment]
Import one of the profiles into Simplify3D and then generate the gcode from Simplify3D using the "Save Toolpaths to Disk".  Then open Sindoh 3DWOX Desktop Software, choose File / Load G-Code, then select the gcode saved from Simplify3D.  Then print the object as normal.  Assure you are using the latest version of Sindoh 3DWOX Desktop Software to allow you to import and print the gcode files.
